version: "3"

tasks:
    run:
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run .

    build:
        desc: Build and compress the app for windows
        cmds:
        # - GOFLAGS=-mod=mod go build -o bin/gopher-desktop .
        - fyne package
        - upx -9 pz-bodycount-server.exe