version: "3"

tasks:
    run:
        desc: Run the app
        cmds:
          - go run .

    build:
        desc: Build and compress the app for windows
        cmds:
          - fyne package
          - upx -9 pz-bodycount-server.exe