name: Build

on:
  create:

jobs:

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
      
    - name: Build
      run: fyne package -os windows
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pz-bodycount-server
        path: |
          pz-bodycount-server.exe
          config.txt
          template.html.example
